# Generated by Django 4.0 on 2021-12-15 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzamenu', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Pizzamenu',
        ),
    ]
